"""add tenant_id to link and device

Revision ID: 2e696eccd30d
Revises: 6e6b8fc5bebe
Create Date: 2026-05-02 15:54:01.689256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e696eccd30d'
down_revision = '6e6b8fc5bebe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # carriers
    op.add_column('carriers', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_carriers_tenant_id'), 'carriers', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'carriers', 'tenants', ['tenant_id'], ['id'])

    # devices
    op.add_column('devices', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'devices', 'tenants', ['tenant_id'], ['id'])

    # links
    op.add_column('links', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_links_tenant_id'), 'links', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'links', 'tenants', ['tenant_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.drop_index(op.f('ix_links_tenant_id'), table_name='links')
    op.drop_column('links', 'tenant_id')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_column('devices', 'tenant_id')
    op.drop_constraint(None, 'carriers', type_='foreignkey')
    op.drop_index(op.f('ix_carriers_tenant_id'), table_name='carriers')
    op.drop_column('carriers', 'tenant_id')
    # ### end Alembic commands ###
