"""add tenant_id to sites

Revision ID: 6e6b8fc5bebe
Revises: b7a8c9d0e1f2
Create Date: 2026-05-02 14:56:35.933482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6b8fc5bebe'
down_revision = 'b7a8c9d0e1f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_sites_tenant_id'), 'sites', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'sites', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.drop_index(op.f('ix_sites_tenant_id'), table_name='sites')
    op.drop_column('sites', 'tenant_id')
    # ### end Alembic commands ###
