"""add network telemetry ingestion

Revision ID: acfdcd08152c
Revises: f443727b2ade
Create Date: 2026-05-30 19:42:10.591338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfdcd08152c'
down_revision = 'f443727b2ade'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snmp_traps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('source_ip', sa.String(length=50), nullable=False),
    sa.Column('snmp_version', sa.String(length=20), nullable=False),
    sa.Column('enterprise_oid', sa.String(length=255), nullable=True),
    sa.Column('trap_oid', sa.String(length=255), nullable=False),
    sa.Column('uptime_ticks', sa.BigInteger(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('varbinds', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snmp_traps_device_id'), 'snmp_traps', ['device_id'], unique=False)
    op.create_index(op.f('ix_snmp_traps_enterprise_oid'), 'snmp_traps', ['enterprise_oid'], unique=False)
    op.create_index(op.f('ix_snmp_traps_received_at'), 'snmp_traps', ['received_at'], unique=False)
    op.create_index(op.f('ix_snmp_traps_severity'), 'snmp_traps', ['severity'], unique=False)
    op.create_index(op.f('ix_snmp_traps_snmp_version'), 'snmp_traps', ['snmp_version'], unique=False)
    op.create_index(op.f('ix_snmp_traps_source_ip'), 'snmp_traps', ['source_ip'], unique=False)
    op.create_index(op.f('ix_snmp_traps_tenant_id'), 'snmp_traps', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_snmp_traps_trap_oid'), 'snmp_traps', ['trap_oid'], unique=False)
    op.create_table('syslog_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('source_ip', sa.String(length=50), nullable=False),
    sa.Column('transport', sa.String(length=20), nullable=False),
    sa.Column('syslog_format', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('facility', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('app_name', sa.String(length=100), nullable=True),
    sa.Column('procid', sa.String(length=100), nullable=True),
    sa.Column('msgid', sa.String(length=100), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('parse_status', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syslog_messages_app_name'), 'syslog_messages', ['app_name'], unique=False)
    op.create_index(op.f('ix_syslog_messages_device_id'), 'syslog_messages', ['device_id'], unique=False)
    op.create_index(op.f('ix_syslog_messages_event_timestamp'), 'syslog_messages', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_syslog_messages_facility'), 'syslog_messages', ['facility'], unique=False)
    op.create_index(op.f('ix_syslog_messages_hostname'), 'syslog_messages', ['hostname'], unique=False)
    op.create_index(op.f('ix_syslog_messages_msgid'), 'syslog_messages', ['msgid'], unique=False)
    op.create_index(op.f('ix_syslog_messages_parse_status'), 'syslog_messages', ['parse_status'], unique=False)
    op.create_index(op.f('ix_syslog_messages_received_at'), 'syslog_messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_syslog_messages_severity'), 'syslog_messages', ['severity'], unique=False)
    op.create_index(op.f('ix_syslog_messages_source_ip'), 'syslog_messages', ['source_ip'], unique=False)
    op.create_index(op.f('ix_syslog_messages_syslog_format'), 'syslog_messages', ['syslog_format'], unique=False)
    op.create_index(op.f('ix_syslog_messages_tenant_id'), 'syslog_messages', ['tenant_id'], unique=False)
    op.create_table('flow_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('interface_id', sa.UUID(), nullable=True),
    sa.Column('link_id', sa.UUID(), nullable=True),
    sa.Column('exporter_ip', sa.String(length=50), nullable=False),
    sa.Column('flow_protocol', sa.String(length=50), nullable=False),
    sa.Column('source_ip', sa.String(length=50), nullable=False),
    sa.Column('destination_ip', sa.String(length=50), nullable=False),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('ip_protocol', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('packets', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_records_destination_ip'), 'flow_records', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_flow_records_destination_port'), 'flow_records', ['destination_port'], unique=False)
    op.create_index(op.f('ix_flow_records_device_id'), 'flow_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_flow_records_direction'), 'flow_records', ['direction'], unique=False)
    op.create_index(op.f('ix_flow_records_ended_at'), 'flow_records', ['ended_at'], unique=False)
    op.create_index(op.f('ix_flow_records_exporter_ip'), 'flow_records', ['exporter_ip'], unique=False)
    op.create_index(op.f('ix_flow_records_flow_protocol'), 'flow_records', ['flow_protocol'], unique=False)
    op.create_index(op.f('ix_flow_records_interface_id'), 'flow_records', ['interface_id'], unique=False)
    op.create_index(op.f('ix_flow_records_ip_protocol'), 'flow_records', ['ip_protocol'], unique=False)
    op.create_index(op.f('ix_flow_records_link_id'), 'flow_records', ['link_id'], unique=False)
    op.create_index(op.f('ix_flow_records_received_at'), 'flow_records', ['received_at'], unique=False)
    op.create_index(op.f('ix_flow_records_source_ip'), 'flow_records', ['source_ip'], unique=False)
    op.create_index(op.f('ix_flow_records_source_port'), 'flow_records', ['source_port'], unique=False)
    op.create_index(op.f('ix_flow_records_started_at'), 'flow_records', ['started_at'], unique=False)
    op.create_index(op.f('ix_flow_records_tenant_id'), 'flow_records', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flow_records_tenant_id'), table_name='flow_records')
    op.drop_index(op.f('ix_flow_records_started_at'), table_name='flow_records')
    op.drop_index(op.f('ix_flow_records_source_port'), table_name='flow_records')
    op.drop_index(op.f('ix_flow_records_source_ip'), table_name='flow_records')
    op.drop_index(op.f('ix_flow_records_received_at'), table_name='flow_records')
    op.drop_index(op.f('ix_flow_records_link_id'), table_name='flow_records')
    op.drop_index(op.f('ix_flow_records_ip_protocol'), table_name='flow_records')
    op.drop_index(op.f('ix_flow_records_interface_id'), table_name='flow_records')
    op.drop_index(op.f('ix_flow_records_flow_protocol'), table_name='flow_records')
    op.drop_index(op.f('ix_flow_records_exporter_ip'), table_name='flow_records')
    op.drop_index(op.f('ix_flow_records_ended_at'), table_name='flow_records')
    op.drop_index(op.f('ix_flow_records_direction'), table_name='flow_records')
    op.drop_index(op.f('ix_flow_records_device_id'), table_name='flow_records')
    op.drop_index(op.f('ix_flow_records_destination_port'), table_name='flow_records')
    op.drop_index(op.f('ix_flow_records_destination_ip'), table_name='flow_records')
    op.drop_table('flow_records')
    op.drop_index(op.f('ix_syslog_messages_tenant_id'), table_name='syslog_messages')
    op.drop_index(op.f('ix_syslog_messages_syslog_format'), table_name='syslog_messages')
    op.drop_index(op.f('ix_syslog_messages_source_ip'), table_name='syslog_messages')
    op.drop_index(op.f('ix_syslog_messages_severity'), table_name='syslog_messages')
    op.drop_index(op.f('ix_syslog_messages_received_at'), table_name='syslog_messages')
    op.drop_index(op.f('ix_syslog_messages_parse_status'), table_name='syslog_messages')
    op.drop_index(op.f('ix_syslog_messages_msgid'), table_name='syslog_messages')
    op.drop_index(op.f('ix_syslog_messages_hostname'), table_name='syslog_messages')
    op.drop_index(op.f('ix_syslog_messages_facility'), table_name='syslog_messages')
    op.drop_index(op.f('ix_syslog_messages_event_timestamp'), table_name='syslog_messages')
    op.drop_index(op.f('ix_syslog_messages_device_id'), table_name='syslog_messages')
    op.drop_index(op.f('ix_syslog_messages_app_name'), table_name='syslog_messages')
    op.drop_table('syslog_messages')
    op.drop_index(op.f('ix_snmp_traps_trap_oid'), table_name='snmp_traps')
    op.drop_index(op.f('ix_snmp_traps_tenant_id'), table_name='snmp_traps')
    op.drop_index(op.f('ix_snmp_traps_source_ip'), table_name='snmp_traps')
    op.drop_index(op.f('ix_snmp_traps_snmp_version'), table_name='snmp_traps')
    op.drop_index(op.f('ix_snmp_traps_severity'), table_name='snmp_traps')
    op.drop_index(op.f('ix_snmp_traps_received_at'), table_name='snmp_traps')
    op.drop_index(op.f('ix_snmp_traps_enterprise_oid'), table_name='snmp_traps')
    op.drop_index(op.f('ix_snmp_traps_device_id'), table_name='snmp_traps')
    op.drop_table('snmp_traps')
    # ### end Alembic commands ###
