"""add ai native noc core foundation

Revision ID: f443727b2ade
Revises: c41d9a72e6f5
Create Date: 2026-05-30 19:07:40.710882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f443727b2ade'
down_revision = 'c41d9a72e6f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_metric_name'), 'alert_rules', ['metric_name'], unique=False)
    op.create_index(op.f('ix_alert_rules_priority'), 'alert_rules', ['priority'], unique=False)
    op.create_index(op.f('ix_alert_rules_resource_type'), 'alert_rules', ['resource_type'], unique=False)
    op.create_index(op.f('ix_alert_rules_severity'), 'alert_rules', ['severity'], unique=False)
    op.create_index(op.f('ix_alert_rules_status'), 'alert_rules', ['status'], unique=False)
    op.create_index(op.f('ix_alert_rules_tenant_id'), 'alert_rules', ['tenant_id'], unique=False)
    op.create_table('metric_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_samples_metric_name'), 'metric_samples', ['metric_name'], unique=False)
    op.create_index(op.f('ix_metric_samples_resource_id'), 'metric_samples', ['resource_id'], unique=False)
    op.create_index(op.f('ix_metric_samples_resource_type'), 'metric_samples', ['resource_type'], unique=False)
    op.create_index(op.f('ix_metric_samples_sampled_at'), 'metric_samples', ['sampled_at'], unique=False)
    op.create_index(op.f('ix_metric_samples_tenant_id'), 'metric_samples', ['tenant_id'], unique=False)
    op.create_table('monitoring_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_checks_check_type'), 'monitoring_checks', ['check_type'], unique=False)
    op.create_index(op.f('ix_monitoring_checks_resource_id'), 'monitoring_checks', ['resource_id'], unique=False)
    op.create_index(op.f('ix_monitoring_checks_resource_type'), 'monitoring_checks', ['resource_type'], unique=False)
    op.create_index(op.f('ix_monitoring_checks_status'), 'monitoring_checks', ['status'], unique=False)
    op.create_index(op.f('ix_monitoring_checks_tenant_id'), 'monitoring_checks', ['tenant_id'], unique=False)
    op.create_table('policy_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('effect', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=True),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_rules_action_type'), 'policy_rules', ['action_type'], unique=False)
    op.create_index(op.f('ix_policy_rules_effect'), 'policy_rules', ['effect'], unique=False)
    op.create_index(op.f('ix_policy_rules_scope'), 'policy_rules', ['scope'], unique=False)
    op.create_index(op.f('ix_policy_rules_status'), 'policy_rules', ['status'], unique=False)
    op.create_index(op.f('ix_policy_rules_target_type'), 'policy_rules', ['target_type'], unique=False)
    op.create_index(op.f('ix_policy_rules_tenant_id'), 'policy_rules', ['tenant_id'], unique=False)
    op.create_table('runbooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('expected_evidence', sa.JSON(), nullable=True),
    sa.Column('rollback_guidance', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runbooks_resource_type'), 'runbooks', ['resource_type'], unique=False)
    op.create_index(op.f('ix_runbooks_severity'), 'runbooks', ['severity'], unique=False)
    op.create_index(op.f('ix_runbooks_status'), 'runbooks', ['status'], unique=False)
    op.create_index(op.f('ix_runbooks_tenant_id'), 'runbooks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_runbooks_trigger_type'), 'runbooks', ['trigger_type'], unique=False)
    op.create_table('check_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('monitoring_check_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitoring_check_id'], ['monitoring_checks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_results_checked_at'), 'check_results', ['checked_at'], unique=False)
    op.create_index(op.f('ix_check_results_monitoring_check_id'), 'check_results', ['monitoring_check_id'], unique=False)
    op.create_index(op.f('ix_check_results_status'), 'check_results', ['status'], unique=False)
    op.create_index(op.f('ix_check_results_tenant_id'), 'check_results', ['tenant_id'], unique=False)
    op.create_table('ai_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('ai_provider_config_id', sa.UUID(), nullable=False),
    sa.Column('agent_action_id', sa.UUID(), nullable=True),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_context', sa.JSON(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_action_id'], ['agent_actions.id'], ),
    sa.ForeignKeyConstraint(['ai_provider_config_id'], ['ai_provider_configs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runs_agent_action_id'), 'ai_runs', ['agent_action_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_ai_provider_config_id'), 'ai_runs', ['ai_provider_config_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_purpose'), 'ai_runs', ['purpose'], unique=False)
    op.create_index(op.f('ix_ai_runs_status'), 'ai_runs', ['status'], unique=False)
    op.create_index(op.f('ix_ai_runs_target_id'), 'ai_runs', ['target_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_target_type'), 'ai_runs', ['target_type'], unique=False)
    op.create_index(op.f('ix_ai_runs_tenant_id'), 'ai_runs', ['tenant_id'], unique=False)
    op.create_table('change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('agent_action_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('planned_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_action_id'], ['agent_actions.id'], ),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_requests_agent_action_id'), 'change_requests', ['agent_action_id'], unique=False)
    op.create_index(op.f('ix_change_requests_approved_by_user_id'), 'change_requests', ['approved_by_user_id'], unique=False)
    op.create_index(op.f('ix_change_requests_incident_id'), 'change_requests', ['incident_id'], unique=False)
    op.create_index(op.f('ix_change_requests_requested_by_user_id'), 'change_requests', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_change_requests_risk_level'), 'change_requests', ['risk_level'], unique=False)
    op.create_index(op.f('ix_change_requests_status'), 'change_requests', ['status'], unique=False)
    op.create_index(op.f('ix_change_requests_tenant_id'), 'change_requests', ['tenant_id'], unique=False)
    op.create_table('automation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_action_id', sa.UUID(), nullable=True),
    sa.Column('change_request_id', sa.UUID(), nullable=True),
    sa.Column('automation_type', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_action_id'], ['agent_actions.id'], ),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_runs_agent_action_id'), 'automation_runs', ['agent_action_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_automation_type'), 'automation_runs', ['automation_type'], unique=False)
    op.create_index(op.f('ix_automation_runs_change_request_id'), 'automation_runs', ['change_request_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_status'), 'automation_runs', ['status'], unique=False)
    op.create_index(op.f('ix_automation_runs_target_id'), 'automation_runs', ['target_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_target_type'), 'automation_runs', ['target_type'], unique=False)
    op.create_index(op.f('ix_automation_runs_tenant_id'), 'automation_runs', ['tenant_id'], unique=False)
    op.alter_column('carriers', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('devices', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('links', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('devices', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('carriers', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_automation_runs_tenant_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_target_type'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_target_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_status'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_change_request_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_automation_type'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_agent_action_id'), table_name='automation_runs')
    op.drop_table('automation_runs')
    op.drop_index(op.f('ix_change_requests_tenant_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_status'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_risk_level'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_requested_by_user_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_incident_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_approved_by_user_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_agent_action_id'), table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index(op.f('ix_ai_runs_tenant_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_target_type'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_target_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_status'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_purpose'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_ai_provider_config_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_agent_action_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_check_results_tenant_id'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_status'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_monitoring_check_id'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_checked_at'), table_name='check_results')
    op.drop_table('check_results')
    op.drop_index(op.f('ix_runbooks_trigger_type'), table_name='runbooks')
    op.drop_index(op.f('ix_runbooks_tenant_id'), table_name='runbooks')
    op.drop_index(op.f('ix_runbooks_status'), table_name='runbooks')
    op.drop_index(op.f('ix_runbooks_severity'), table_name='runbooks')
    op.drop_index(op.f('ix_runbooks_resource_type'), table_name='runbooks')
    op.drop_table('runbooks')
    op.drop_index(op.f('ix_policy_rules_tenant_id'), table_name='policy_rules')
    op.drop_index(op.f('ix_policy_rules_target_type'), table_name='policy_rules')
    op.drop_index(op.f('ix_policy_rules_status'), table_name='policy_rules')
    op.drop_index(op.f('ix_policy_rules_scope'), table_name='policy_rules')
    op.drop_index(op.f('ix_policy_rules_effect'), table_name='policy_rules')
    op.drop_index(op.f('ix_policy_rules_action_type'), table_name='policy_rules')
    op.drop_table('policy_rules')
    op.drop_index(op.f('ix_monitoring_checks_tenant_id'), table_name='monitoring_checks')
    op.drop_index(op.f('ix_monitoring_checks_status'), table_name='monitoring_checks')
    op.drop_index(op.f('ix_monitoring_checks_resource_type'), table_name='monitoring_checks')
    op.drop_index(op.f('ix_monitoring_checks_resource_id'), table_name='monitoring_checks')
    op.drop_index(op.f('ix_monitoring_checks_check_type'), table_name='monitoring_checks')
    op.drop_table('monitoring_checks')
    op.drop_index(op.f('ix_metric_samples_tenant_id'), table_name='metric_samples')
    op.drop_index(op.f('ix_metric_samples_sampled_at'), table_name='metric_samples')
    op.drop_index(op.f('ix_metric_samples_resource_type'), table_name='metric_samples')
    op.drop_index(op.f('ix_metric_samples_resource_id'), table_name='metric_samples')
    op.drop_index(op.f('ix_metric_samples_metric_name'), table_name='metric_samples')
    op.drop_table('metric_samples')
    op.drop_index(op.f('ix_alert_rules_tenant_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_status'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_severity'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_resource_type'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_priority'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_metric_name'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
